<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Arjun" failures="1" tests="6" name="crm.comcast.listener.RetrySampleTest" time="47.870" errors="0" timestamp="2024-05-17T13:35:06 IST" skipped="5">
  <testcase classname="crm.comcast.listener.RetrySampleTest" name="createContact" time="7.909">
    <skipped/>
  </testcase> <!-- createContact -->
  <system-out/>
  <testcase classname="crm.comcast.listener.RetrySampleTest" name="createContact" time="7.930">
    <skipped/>
  </testcase> <!-- createContact -->
  <system-out/>
  <testcase classname="crm.comcast.listener.RetrySampleTest" name="createContact" time="7.926">
    <failure message="expected [Home] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Home] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at crm.comcast.listener.RetrySampleTest.createContact(RetrySampleTest.java:14)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createContact -->
  <system-out/>
  <testcase classname="crm.comcast.listener.RetrySampleTest" name="createContact" time="8.088">
    <skipped/>
  </testcase> <!-- createContact -->
  <system-out/>
  <testcase classname="crm.comcast.listener.RetrySampleTest" name="createContact" time="7.691">
    <skipped/>
  </testcase> <!-- createContact -->
  <system-out/>
  <testcase classname="crm.comcast.listener.RetrySampleTest" name="createContact" time="8.326">
    <skipped/>
  </testcase> <!-- createContact -->
  <system-out/>
</testsuite> <!-- crm.comcast.listener.RetrySampleTest -->
